from io import BytesIO
from html import escape
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


BRAND_LOGO = Path(__file__).resolve().parents[2] / "assets" / "broadcast-tool-pro-logo.png"


def generate_public_xmltv_report(payload: dict, language: str = "en") -> bytes:
    spanish = language == "es"
    copy = {
        "title": "Reporte básico de validación XMLTV" if spanish else "Basic XMLTV Validation Report",
        "format": "FORMATO XMLTV" if spanish else "XMLTV FORMAT",
        "operations": "PREPARACIÓN OPERATIVA" if spanish else "OPERATIONAL READINESS",
        "profile": "PERFIL DE ENTREGA BTP" if spanish else "BTP DELIVERY PROFILE",
        "passed": "Aprobado" if spanish else "Passed",
        "attention": "Requiere atención" if spanish else "Needs attention",
        "ready": "Listo" if spanish else "Ready",
        "review": "Revisión recomendada" if spanish else "Review recommended",
        "channels": "Canales" if spanish else "Channels",
        "programmes": "Programas" if spanish else "Programmes",
        "findings": "Hallazgos" if spanish else "Findings",
        "layer": "Capa" if spanish else "Layer",
        "severity": "Severidad" if spanish else "Severity",
        "rule": "Regla" if spanish else "Rule",
        "line": "Línea" if spanish else "Line",
        "message": "Mensaje" if spanish else "Message",
        "none": "No se encontraron hallazgos." if spanish else "No findings were identified.",
        "footer": "Generado por Broadcast Tool Pro · Validador XMLTV gratuito" if spanish else "Generated by Broadcast Tool Pro · Free XMLTV Validator",
    }
    xmltv = payload.get("xmltv") or {}
    operations = payload.get("operational") or {}
    profile = payload.get("btp_profile") or {}
    output = BytesIO()
    document = SimpleDocTemplate(
        output,
        pagesize=letter,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.45 * inch,
        bottomMargin=0.62 * inch,
        title=copy["title"],
        author="Broadcast Tool Pro",
        pageCompression=0,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("BTPTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=19, leading=23, textColor=colors.HexColor("#102A43"))
    body = ParagraphStyle("BTPBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=7.5, leading=10, textColor=colors.HexColor("#243B53"))
    summary = [
        [copy["format"], copy["operations"], copy["profile"]],
        [copy["passed"] if payload.get("valid") else copy["attention"], copy["ready"] if payload.get("operational_ready") else copy["review"], f'{profile.get("score", 0)}/100'],
        [f'{xmltv.get("critical", 0)} critical · {xmltv.get("errors", 0)} errors', f'{operations.get("errors", 0)} errors · {operations.get("warnings", 0)} warnings', f'{profile.get("recommendations", 0)} recommendations'],
    ]
    summary_table = Table(summary, colWidths=[2.33 * inch] * 3)
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#102A43")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#EAF2FF")),
        ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor("#102A43")),
        ("FONTNAME", (0, 0), (-1, 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D7E1EC")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    rows = [[copy["layer"], copy["severity"], copy["rule"], copy["line"], copy["message"]]]
    for label, section in ((copy["format"], xmltv), (copy["operations"], operations), (copy["profile"], profile)):
        for issue in section.get("issues") or []:
            rows.append([label, issue.get("severity", ""), issue.get("rule_id", ""), issue.get("row") or "—", Paragraph(escape(str(issue.get("message") or "")), body)])
    if len(rows) == 1:
        rows.append(["—", "—", "—", "—", copy["none"]])
    issues_table = Table(rows, colWidths=[1.15 * inch, 0.7 * inch, 0.65 * inch, 0.4 * inch, 4.1 * inch], repeatRows=1)
    issues_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#102A43")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 6.8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D7E1EC")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7FAFC")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story = [
        Image(str(BRAND_LOGO), width=2.7 * inch, height=0.59 * inch),
        Spacer(1, 10),
        Paragraph(copy["title"], title_style),
        Paragraph(f'{escape(str(payload.get("filename") or "XMLTV file"))} · {copy["channels"]}: {payload.get("channels", 0)} · {copy["programmes"]}: {payload.get("programmes", 0)}', body),
        Spacer(1, 12), summary_table, Spacer(1, 14),
        Paragraph(copy["findings"], ParagraphStyle("Section", parent=title_style, fontSize=12, leading=15)),
        Spacer(1, 6), issues_table,
    ]

    def footer(canvas, _doc):
        canvas.saveState()
        canvas.setStrokeColor(colors.HexColor("#D7E1EC"))
        canvas.line(0.5 * inch, 0.42 * inch, 8.0 * inch, 0.42 * inch)
        canvas.setFillColor(colors.HexColor("#627D98"))
        canvas.setFont("Helvetica", 7)
        canvas.drawString(0.5 * inch, 0.25 * inch, copy["footer"])
        canvas.drawRightString(8.0 * inch, 0.25 * inch, str(canvas.getPageNumber()))
        canvas.restoreState()

    document.build(story, onFirstPage=footer, onLaterPages=footer)
    return output.getvalue()
