from datetime import timedelta
from io import BytesIO
from pathlib import Path
from re import sub

from openpyxl import Workbook
from openpyxl.drawing.image import Image
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from backend.services.traffic.playlist import PlaylistEvent

BRAND_LOGO = (
    Path(__file__).resolve().parents[2]
    / "assets"
    / "broadcast-tool-pro-logo.png"
)

LABELS = {
    "en": {
        "sheet": "Pre Log",
        "title": "Pre Log",
        "postlog_title": "Post Log — Broadcast Certification",
        "channel": "Channel Name",
        "product": "Product",
        "asset": "Asset ID",
        "date": "Date",
        "time": "Time",
        "duration": "Duration",
        "agency": "Agency",
        "generated": "Generated by Broadcast Tool Pro",
        "total_airings": "Total Airings",
    },
    "es": {
        "sheet": "Pre Log",
        "title": "Pre Log",
        "postlog_title": "Post Log — Certificación de Emisiones",
        "channel": "Nombre del canal",
        "product": "Producto",
        "asset": "Identificador del elemento",
        "date": "Fecha",
        "time": "Hora",
        "duration": "Duración",
        "agency": "Agencia",
        "generated": "Generado por Broadcast Tool Pro",
        "total_airings": "Total de Emisiones",
    },
}


def safe_prelog_filename(
    channel_name: str,
    start_date: str | None,
    end_date: str | None,
) -> str:
    slug = sub(r"[^a-z0-9]+", "-", channel_name.lower()).strip("-")
    dates = "-".join(
        value.replace("-", "")
        for value in (start_date, end_date)
        if value
    )
    suffix = f"-{dates}" if dates else ""
    return f"prelog-{slug or 'channel'}{suffix}.xlsx"


def _duration_value(value: str | None) -> timedelta | None:
    if not value:
        return None

    parts = value.split(":")
    if len(parts) != 3:
        return None

    try:
        hours, minutes, seconds = (int(part) for part in parts)
    except ValueError:
        return None

    return timedelta(hours=hours, minutes=minutes, seconds=seconds)


def generate_prelog_workbook(
    events: list[PlaylistEvent],
    channel_name: str,
    language: str = "en",
    product: str | None = None,
    agency: str | None = None,
    logo_content: bytes | None = None,
    report_type: str = "prelog",
) -> bytes:
    if not events:
        raise ValueError("At least one scheduled event is required.")
    if not channel_name.strip():
        raise ValueError("Channel Name is required.")
    if language not in LABELS:
        raise ValueError("Report language must be English or Spanish.")

    labels = LABELS[language]
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = labels["sheet"]
    worksheet.sheet_view.showGridLines = False
    include_product = bool(product and product.strip())
    include_agency = bool(agency and agency.strip())
    columns = [
        labels["channel"],
    ]
    if include_product:
        columns.append(labels["product"])
    columns.extend([
        labels["asset"],
        labels["date"],
        labels["time"],
        labels["duration"],
    ])
    if include_agency:
        columns.append(labels["agency"])

    last_column = get_column_letter(len(columns))
    title_end_column = get_column_letter(max(3, len(columns) - 1))
    if report_type not in {"prelog", "postlog"}:
        raise ValueError("Unsupported report type.")
    worksheet.merge_cells(f"C1:{title_end_column}1")
    worksheet["C1"] = (
        labels["postlog_title"]
        if report_type == "postlog"
        else labels["title"]
    )
    worksheet["C1"].font = Font(
        name="Aptos Display",
        size=20,
        bold=True,
        color="102A43",
    )
    worksheet["C1"].alignment = Alignment(vertical="center")
    worksheet.row_dimensions[1].height = 34
    brand_logo = Image(str(BRAND_LOGO))
    brand_scale = min(175 / brand_logo.width, 38 / brand_logo.height)
    brand_logo.width = round(brand_logo.width * brand_scale)
    brand_logo.height = round(brand_logo.height * brand_scale)
    worksheet.add_image(brand_logo, "A1")

    worksheet.merge_cells(f"C2:{title_end_column}2")
    worksheet["C2"] = channel_name.strip()
    worksheet["C2"].font = Font(
        name="Aptos",
        size=12,
        bold=True,
        color="2563EB",
    )

    first_airing = min(event.air_datetime for event in events)
    last_airing = max(event.air_datetime for event in events)
    worksheet.merge_cells(f"C3:{title_end_column}3")
    worksheet["C3"] = (
        f"{first_airing:%B %d, %Y %H:%M} – "
        f"{last_airing:%B %d, %Y %H:%M}"
    )
    worksheet["C3"].font = Font(name="Aptos", size=10, color="64748B")

    header_row = 5
    asset_column = 3 if include_product else 2
    for column, value in enumerate(columns, start=1):
        cell = worksheet.cell(header_row, column, value)
        cell.font = Font(name="Aptos", size=10, bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1D4ED8")
        cell.alignment = Alignment(
            horizontal="left" if column == asset_column else "center",
            vertical="center",
        )

    thin_border = Border(
        bottom=Side(style="thin", color="D9E2EC"),
    )
    for row_number, event in enumerate(events, start=header_row + 1):
        air_datetime = event.air_datetime.replace(tzinfo=None)
        values = [
            channel_name.strip(),
        ]
        if include_product:
            values.append(product.strip())
        values.extend([
            event.asset_id,
            air_datetime.date(),
            air_datetime.time(),
            _duration_value(event.duration) or event.duration,
        ])
        if include_agency:
            values.append(agency.strip())

        for column, value in enumerate(values, start=1):
            cell = worksheet.cell(row_number, column, value)
            cell.font = Font(name="Aptos", size=10, color="243B53")
            cell.border = thin_border
            cell.alignment = Alignment(
                horizontal=(
                    "left" if column == asset_column else "center"
                ),
                vertical="center",
            )
            if row_number % 2 == 0:
                cell.fill = PatternFill("solid", fgColor="F8FAFC")

        date_column = 4 if include_product else 3
        time_column = date_column + 1
        duration_column = time_column + 1
        worksheet.cell(row_number, date_column).number_format = "mm/dd/yyyy"
        worksheet.cell(row_number, time_column).number_format = "hh:mm:ss"
        if isinstance(
            worksheet.cell(row_number, duration_column).value,
            timedelta,
        ):
            worksheet.cell(
                row_number,
                duration_column,
            ).number_format = "[h]:mm:ss"

    footer_row = header_row + len(events) + 2
    worksheet.merge_cells(f"A{footer_row}:{last_column}{footer_row}")
    footer_text = labels["generated"]
    if report_type == "postlog":
        footer_text = (
            f"{labels['total_airings']}: {len(events)} · {footer_text}"
        )
    worksheet.cell(footer_row, 1, footer_text)
    worksheet.cell(footer_row, 1).font = Font(
        name="Aptos",
        size=9,
        italic=True,
        color="829AB1",
    )

    widths = [22]
    if include_product:
        widths.append(24)
    widths.extend([38, 14, 14, 14])
    if include_agency:
        widths.append(24)
    for column, width in enumerate(widths[:len(columns)], start=1):
        worksheet.column_dimensions[get_column_letter(column)].width = width

    worksheet.auto_filter.ref = (
        f"A{header_row}:{last_column}{header_row + len(events)}"
    )
    worksheet.freeze_panes = f"A{header_row + 1}"
    worksheet.print_title_rows = f"1:{header_row}"
    worksheet.sheet_properties.pageSetUpPr.fitToPage = True
    worksheet.page_setup.orientation = "landscape"
    worksheet.page_setup.fitToWidth = 1
    worksheet.page_setup.fitToHeight = 0
    worksheet.page_margins.left = 0.25
    worksheet.page_margins.right = 0.25
    worksheet.page_margins.top = 0.4
    worksheet.page_margins.bottom = 0.4

    if logo_content:
        try:
            logo = Image(BytesIO(logo_content))
            scale = min(150 / logo.width, 58 / logo.height, 1)
            logo.width = round(logo.width * scale)
            logo.height = round(logo.height * scale)
            worksheet.add_image(logo, f"{last_column}1")
        except Exception as exc:
            raise ValueError(
                "The logo must be a valid PNG, JPG, or JPEG image."
            ) from exc

    output = BytesIO()
    workbook.save(output)
    return output.getvalue()
