from datetime import timedelta
from io import BytesIO
from re import sub

from openpyxl import Workbook
from openpyxl.drawing.image import Image
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from backend.services.traffic.playlist import PlaylistEvent


LABELS = {
    "en": {
        "sheet": "Pre Log",
        "title": "Pre Log",
        "channel": "Channel Name",
        "asset": "Asset ID",
        "date_time": "Date / Time",
        "duration": "Duration",
        "agency": "Agency",
        "generated": "Generated by Broadcast Tool Pro",
    },
    "es": {
        "sheet": "Pre Log",
        "title": "Pre Log",
        "channel": "Nombre del canal",
        "asset": "Identificador del elemento",
        "date_time": "Fecha / Hora",
        "duration": "Duración",
        "agency": "Agencia",
        "generated": "Generado por Broadcast Tool Pro",
    },
}


def safe_prelog_filename(
    channel_name: str,
    start_date: str | None,
    end_date: str | None,
) -> str:
    slug = sub(r"[^a-z0-9]+", "-", channel_name.lower()).strip("-")
    dates = "-".join(
        value.replace("-", "")
        for value in (start_date, end_date)
        if value
    )
    suffix = f"-{dates}" if dates else ""
    return f"prelog-{slug or 'channel'}{suffix}.xlsx"


def _duration_value(value: str | None) -> timedelta | None:
    if not value:
        return None

    parts = value.split(":")
    if len(parts) != 3:
        return None

    try:
        hours, minutes, seconds = (int(part) for part in parts)
    except ValueError:
        return None

    return timedelta(hours=hours, minutes=minutes, seconds=seconds)


def generate_prelog_workbook(
    events: list[PlaylistEvent],
    channel_name: str,
    language: str = "en",
    agency: str | None = None,
    logo_content: bytes | None = None,
) -> bytes:
    if not events:
        raise ValueError("At least one scheduled event is required.")
    if not channel_name.strip():
        raise ValueError("Channel Name is required.")
    if language not in LABELS:
        raise ValueError("Report language must be English or Spanish.")

    labels = LABELS[language]
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = labels["sheet"]
    worksheet.sheet_view.showGridLines = False
    include_agency = bool(agency and agency.strip())
    columns = [
        labels["channel"],
        labels["asset"],
        labels["date_time"],
        labels["duration"],
    ]
    if include_agency:
        columns.append(labels["agency"])

    last_column = get_column_letter(len(columns))
    worksheet.merge_cells(f"A1:{last_column}1")
    worksheet["A1"] = labels["title"]
    worksheet["A1"].font = Font(
        name="Aptos Display",
        size=22,
        bold=True,
        color="102A43",
    )
    worksheet["A1"].alignment = Alignment(vertical="center")
    worksheet.row_dimensions[1].height = 34

    worksheet.merge_cells(f"A2:{last_column}2")
    worksheet["A2"] = channel_name.strip()
    worksheet["A2"].font = Font(
        name="Aptos",
        size=12,
        bold=True,
        color="2563EB",
    )

    first_airing = min(event.air_datetime for event in events)
    last_airing = max(event.air_datetime for event in events)
    worksheet.merge_cells(f"A3:{last_column}3")
    worksheet["A3"] = (
        f"{first_airing:%B %d, %Y %H:%M} – "
        f"{last_airing:%B %d, %Y %H:%M}"
    )
    worksheet["A3"].font = Font(name="Aptos", size=10, color="64748B")

    header_row = 5
    for column, value in enumerate(columns, start=1):
        cell = worksheet.cell(header_row, column, value)
        cell.font = Font(name="Aptos", size=10, bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1D4ED8")
        cell.alignment = Alignment(vertical="center")

    thin_border = Border(
        bottom=Side(style="thin", color="D9E2EC"),
    )
    for row_number, event in enumerate(events, start=header_row + 1):
        air_datetime = event.air_datetime.replace(tzinfo=None)
        values = [
            channel_name.strip(),
            event.asset_id,
            air_datetime,
            _duration_value(event.duration) or event.duration,
        ]
        if include_agency:
            values.append(agency.strip())

        for column, value in enumerate(values, start=1):
            cell = worksheet.cell(row_number, column, value)
            cell.font = Font(name="Aptos", size=10, color="243B53")
            cell.border = thin_border
            cell.alignment = Alignment(vertical="center")
            if row_number % 2 == 0:
                cell.fill = PatternFill("solid", fgColor="F8FAFC")

        worksheet.cell(row_number, 3).number_format = "mm/dd/yyyy hh:mm:ss"
        if isinstance(worksheet.cell(row_number, 4).value, timedelta):
            worksheet.cell(row_number, 4).number_format = "[h]:mm:ss"

    footer_row = header_row + len(events) + 2
    worksheet.merge_cells(f"A{footer_row}:{last_column}{footer_row}")
    worksheet.cell(footer_row, 1, labels["generated"])
    worksheet.cell(footer_row, 1).font = Font(
        name="Aptos",
        size=9,
        italic=True,
        color="829AB1",
    )

    widths = [22, 38, 24, 14, 24]
    for column, width in enumerate(widths[:len(columns)], start=1):
        worksheet.column_dimensions[get_column_letter(column)].width = width

    worksheet.auto_filter.ref = (
        f"A{header_row}:{last_column}{header_row + len(events)}"
    )
    worksheet.freeze_panes = f"A{header_row + 1}"
    worksheet.print_title_rows = f"1:{header_row}"
    worksheet.sheet_properties.pageSetUpPr.fitToPage = True
    worksheet.page_setup.orientation = "landscape"
    worksheet.page_setup.fitToWidth = 1
    worksheet.page_setup.fitToHeight = 0
    worksheet.page_margins.left = 0.25
    worksheet.page_margins.right = 0.25
    worksheet.page_margins.top = 0.4
    worksheet.page_margins.bottom = 0.4

    if logo_content:
        try:
            logo = Image(BytesIO(logo_content))
            logo.width = min(logo.width, 150)
            logo.height = min(logo.height, 58)
            worksheet.add_image(logo, f"{last_column}1")
        except Exception as exc:
            raise ValueError("The logo must be a valid PNG image.") from exc

    output = BytesIO()
    workbook.save(output)
    return output.getvalue()
